import type { Product } from './types';

export const BANKS: Product[] = [
  {
    id: 'myfin',
    name: 'Bulgarian Elite',
    price: 24900,
    desc: 'ЛИЧНЫЙ IBAN. ЕВРОПЕЙСКИЙ БАНК. ВЫПУСК ЗА 24 ЧАСА',
    badge: 'IBAN',
    badgeColors: 'from-blue-500/40 to-blue-900/10 border-blue-500/20',
    tag: 'Личный IBAN · Instant',
    gradient: 'linear-gradient(135deg, #0a1b3d 0%, #0a0c04 100%)',
    deliveryTime: '24ч',
    lto: true,
    fullDesc: 'Полноценный болгарский цифровой банк с личным IBAN. Белое решение для резидентов РФ. Карта выпускается на ваше имя с полным доступом к европейской банковской инфраструктуре.',
    features: [
      { icon: 'credit-card', title: 'Личный IBAN (Болгария)', desc: 'Европейский банковский счёт на ваше имя с полным контролем' },
      { icon: 'smartphone', title: 'Apple / Google Pay', desc: 'Мгновенная привязка к мобильным кошелькам для бесконтактной оплаты' },
      { icon: 'zap', title: 'SEPA Instant переводы', desc: 'Переводы по всей Европе за считанные секунды' },
      { icon: 'shield', title: 'Статус дебетовой карты', desc: 'Полноценная дебетовая Visa с европейской лицензией' },
    ],
  },
  {
    id: 'stables',
    name: 'Ice Vault',
    price: 8900,
    desc: 'ВИРТУАЛЬНАЯ КАРТА. USDC-FIRST. ВЫПУСК ЗА 5 МИНУТ',
    badge: 'USDC',
    badgeColors: 'from-cyan-500/40 to-cyan-900/10 border-cyan-500/20',
    tag: 'Стейблкоины · 5 мин',
    gradient: 'linear-gradient(135deg, #0a1b2b 0%, #0a0c04 100%)',
    deliveryTime: '5 мин',
    lto: true,
    fullDesc: 'Простое решение для оплаты подписок и шопинга. Работает со стейблкоинами. Виртуальная карта выпускается мгновенно.',
    features: [
      { icon: 'wallet', title: 'Фокус на USDC/USDT', desc: 'Основная работа со стейблкоинами — стабильный курс без волатильности' },
      { icon: 'zap', title: 'Мгновенный выпуск', desc: 'Виртуальная карта готова к использованию за 5 минут' },
      { icon: 'percent', title: 'Без абонентской платы', desc: 'Никаких скрытых комиссий и ежемесячных платежей' },
      { icon: 'shield', title: 'L2 интеграция', desc: 'Прозрачность всех операций ончейн через Layer 2' },
    ],
  },
  {
    id: 'wayex',
    name: 'Nomad FX',
    price: 9900,
    desc: 'GLOBAL TRAVEL CARD. ZERO FX. ВЫПУСК ЗА 24 ЧАСА',
    badge: 'VISA',
    badgeColors: 'from-indigo-500/40 to-indigo-900/10 border-indigo-500/20',
    tag: 'Zero FX · Travel',
    gradient: 'linear-gradient(135deg, #05163d 0%, #0a0c04 100%)',
    deliveryTime: '24ч',
    lto: true,
    fullDesc: 'Лаконичный сервис для путешественников. Отсутствие комиссий за конвертацию. Visa Platinum с глобальным охватом.',
    features: [
      { icon: 'globe', title: 'Zero FX Fees', desc: 'Никаких комиссий за конвертацию валют при оплате за границей' },
      { icon: 'credit-card', title: 'Visa Platinum', desc: 'Премиальная карта с расширенными лимитами и привилегиями' },
      { icon: 'zap', title: 'Мгновенный On-ramp', desc: 'Быстрый ввод средств из криптовалюты в фиат' },
      { icon: 'globe', title: 'Глобальный охват', desc: 'Принимается в 200+ странах мира без ограничений' },
    ],
  },
  {
    id: 'coca',
    name: 'Privacy Shield',
    price: 11900,
    desc: 'MPC SECURITY. NON-CUSTODIAL. ВЫПУСК ЗА 24 ЧАСА',
    badge: 'MPC',
    badgeColors: 'from-emerald-500/40 to-emerald-900/10 border-emerald-500/20',
    tag: 'Non-Custodial · Secure',
    gradient: 'linear-gradient(135deg, #1d2e14 0%, #0a0c04 100%)',
    deliveryTime: '24ч',
    lto: true,
    fullDesc: 'Некастодиальный кошелек нового поколения с MPC-технологией. Полный контроль над своими средствами с максимальной безопасностью.',
    features: [
      { icon: 'lock', title: 'Self-Custody', desc: 'Некастодиальный кошелёк — только вы контролируете свои средства' },
      { icon: 'percent', title: 'Кешбэк до 50%', desc: 'Повышенный возврат средств на определённые категории покупок' },
      { icon: 'smartphone', title: 'Вход по биометрии', desc: 'Безопасный вход по отпечатку пальца или Face ID' },
      { icon: 'wallet', title: 'Пассивный доход 6%', desc: 'Стейкинг прямо в приложении с ежедневным начислением' },
    ],
  },
  {
    id: 'emcd',
    name: 'Mining Bridge',
    price: 14900,
    desc: 'СНГ МОСТ. МАЙНИНГ ЭКОСИСТЕМА. ВЫДАЧА ДО 48 ЧАСОВ',
    badge: 'POOL',
    badgeColors: 'from-orange-500/40 to-orange-900/10 border-orange-500/20',
    tag: 'СНГ мост · Майнинг',
    gradient: 'linear-gradient(135deg, #3d240a 0%, #0a0c04 100%)',
    deliveryTime: '48ч',
    lto: false,
    fullDesc: 'Мощная экосистема от майнинг-пула для вывода крипты в реальный мир. Полная лояльность к резидентам РФ и СНГ.',
    features: [
      { icon: 'zap', title: 'Прямой вывод с пула', desc: 'Интеграция с майнинг-инфраструктурой для прямого вывода' },
      { icon: 'wallet', title: 'P2P ликвидность', desc: 'Обмен напрямую между пользователями без посредников' },
      { icon: 'percent', title: 'Coinhold до 14%', desc: 'Высокие ставки на хранение криптовалюты в экосистеме' },
      { icon: 'globe', title: 'Лояльность к РФ', desc: 'Полная поддержка русскоязычных клиентов без ограничений' },
    ],
  },
  {
    id: 'wirex',
    name: 'London Fusion',
    price: 19900,
    desc: 'ПРЕМИУМ ГИБРИД. КЕШБЭК 8%. ВЫДАЧА ДО 48 ЧАСОВ',
    badge: 'PRE',
    badgeColors: 'from-purple-500/40 to-purple-900/10 border-purple-500/20',
    tag: 'Cashback 8% · Premium',
    gradient: 'linear-gradient(135deg, #1b111b 0%, #0a0c04 100%)',
    deliveryTime: '48ч',
    lto: false,
    fullDesc: 'Старейший гибридный сервис, объединяющий фиат и крипту. Металлическая карта с расширенными лимитами и премиальным кешбэком.',
    features: [
      { icon: 'wallet', title: 'Мультивалютные счета', desc: 'Фиат и крипто на одной карте с мгновенной конвертацией' },
      { icon: 'percent', title: 'Cryptoback\u2122 до 8%', desc: 'Кешбэк криптовалютой за каждую покупку — до 8% возврата' },
      { icon: 'credit-card', title: 'Металлическая карта', desc: 'Премиальный физический носитель для VIP-клиентов' },
      { icon: 'shield', title: 'Высокие лимиты', desc: 'Увеличенные лимиты на переводы и снятие наличных' },
    ],
  },
];

export const DROPS: Product[] = [
  {
    id: 'redotpay',
    name: 'Redotpay',
    price: 10000,
    desc: 'АЗИЯ. КРИПТО-БАНК.',
    badge: 'ASIA',
    badgeColors: 'from-red-500/40 to-red-900/10 border-red-500/20',
    tag: 'Крипто-банк · Азия',
    gradient: 'linear-gradient(135deg, #3d0a0a 0%, #0a0c04 100%)',
    deliveryTime: '24ч',
    lto: false,
    img: 'https://staticsource1.redotpay.com/web/img/logo.svg?t=1770172675664',
    fullDesc: 'Азиатский крипто-банк с полной интеграцией. Идеальное решение для работы с азиатскими рынками и криптовалютными операциями.',
    features: [
      { icon: 'globe', title: 'Азиатский крипто-банк', desc: 'Полная интеграция с азиатскими финансовыми рынками' },
      { icon: 'zap', title: 'Мгновенное пополнение', desc: 'Из криптовалюты в фиат за секунды без задержек' },
    ],
  },
  {
    id: 'wise',
    name: 'Wise',
    price: 15000,
    desc: 'ЕВРОПА. ПОПУЛЯРНЫЙ БАНК.',
    badge: 'EUR',
    badgeColors: 'from-emerald-500/40 to-emerald-900/10 border-emerald-500/20',
    tag: 'Европейский банк',
    gradient: 'linear-gradient(135deg, #1d2e14 0%, #0a0c04 100%)',
    deliveryTime: '48ч',
    lto: false,
    img: 'https://companieslogo.com/img/orig/WISE.L_BIG.D-95705462.svg?t=1720244494',
    fullDesc: 'Один из самых популярных банков в Европе. Мультивалютный счёт с выгодными курсами обмена.',
    features: [
      { icon: 'globe', title: 'Европейский банк', desc: 'Один из самых популярных и надёжных банков в Европе' },
      { icon: 'wallet', title: 'Мультивалютный счёт', desc: 'Десятки валют на одном счёте с лучшими курсами обмена' },
    ],
  },
  {
    id: 'revolut',
    name: 'Revolut',
    price: 18000,
    desc: 'ЛУЧШИЙ ЕВРОПЕЙСКИЙ БАНК.',
    badge: 'TOP',
    badgeColors: 'from-slate-400/40 to-slate-900/10 border-slate-400/20',
    tag: 'Лучший необанк',
    gradient: 'linear-gradient(135deg, #1f1f21 0%, #0a0c04 100%)',
    deliveryTime: '48ч',
    lto: false,
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Revolut_logo.svg/960px-Revolut_logo.svg.png',
    fullDesc: 'Лучший европейский необанк по всем рейтингам. Глобальные переводы, инвестиции и крипто — всё в одном приложении.',
    features: [
      { icon: 'credit-card', title: 'Лучший необанк', desc: '№1 в рейтингах европейских необанков с 40М+ клиентами' },
      { icon: 'globe', title: 'Глобальные переводы', desc: 'Мгновенные переводы в 150+ стран мира без скрытых комиссий' },
    ],
  },
];

export const SERVICES: Product[] = [
  {
    id: 'paypal',
    name: 'PayPal',
    price: 7000,
    desc: 'ВЕРИФИКАЦИЯ АККАУНТА ПОД КЛЮЧ',
    badge: 'USA',
    badgeColors: 'from-blue-600/40 to-blue-900/10 border-blue-600/20',
    tag: 'Верификация · Под ключ',
    gradient: 'linear-gradient(135deg, #001c4d 0%, #0a0c04 100%)',
    deliveryTime: '48ч',
    lto: true,
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg',
    fullDesc: 'Полная верификация PayPal аккаунта под ключ. Аккаунт полностью подтверждён и готов к работе с глобальными платежами.',
    features: [
      { icon: 'shield', title: 'Полная верификация', desc: 'Аккаунт полностью подтверждён и готов к приёму и отправке платежей' },
      { icon: 'globe', title: 'Глобальные платежи', desc: 'Принимается миллионами продавцов по всему миру' },
    ],
  },
];

export const EUR_RATE = 90.31;
